import * as fs from 'fs';

import type { FixDraft, FixSuggestion } from './fix-generator';

/**
 * Day 5: render a fix draft as a Markdown report a developer can read.
 *
 * The output is meant to be human-consumed, not fed back into tooling.
 * Grouped by symbol, one block per affected file:line, with the original
 * code, the suggested fix (or an honest "manual review" verdict), and a
 * plain-English explanation.
 */

const REPORTS_DIR = 'reports';

/** Construct a stable, sortable filename for one run. */
export function reportFileName(draft: FixDraft): string {
  const safePackage = draft.packageName.replace(/[^a-zA-Z0-9._-]/g, '_');
  const ts = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
  return `${REPORTS_DIR}/fix-report-${safePackage}-${draft.oldVersion}-to-${draft.newVersion}-${ts}.md`;
}

function confidenceLabel(s: FixSuggestion): string {
  switch (s.confidence) {
    case 'high':
      return 'HIGH';
    case 'medium':
      return 'MEDIUM';
    case 'low':
      return 'LOW';
    case 'requires-manual-review':
      return 'MANUAL REVIEW';
    default:
      return s.confidence;
  }
}

function fenceLang(suggestedCode: string | null): string {
  // Pick a fence language that matches what the file looks like. Most
  // usages in the demo are TypeScript; if the path looks like JS only,
  // use javascript. Otherwise default to ts which is fine for either.
  if (!suggestedCode) return 'ts';
  return 'ts';
}

function renderOneSuggestion(s: FixSuggestion): string {
  const lines: string[] = [];

  lines.push(`#### \`${s.file}\`:${s.line}`);
  lines.push('');
  lines.push(`- Confidence: **${confidenceLabel(s)}**`);
  if (s.error) {
    lines.push(`- Generation note: ${s.error}`);
  }
  lines.push('');
  lines.push('**Original:**');
  lines.push('');
  lines.push('```' + fenceLang(s.originalCode));
  lines.push(s.originalCode);
  lines.push('```');
  lines.push('');

  if (s.suggestedCode !== null) {
    lines.push('**Suggested fix:**');
    lines.push('');
    lines.push('```' + fenceLang(s.suggestedCode));
    lines.push(s.suggestedCode);
    lines.push('```');
    lines.push('');
  } else {
    lines.push('**Suggested fix:** _none — see explanation_');
    lines.push('');
  }

  lines.push('**Explanation:**');
  lines.push('');
  lines.push(s.explanation || '_(no explanation provided)_');
  lines.push('');

  return lines.join('\n');
}

function renderSymbolBlock(symbolName: string, suggestions: FixSuggestion[]): string {
  const lines: string[] = [];
  const first = suggestions[0];

  lines.push(`## \`${symbolName}\``);
  lines.push('');
  if (first.symbolReason) {
    lines.push(`> ${first.symbolReason}`);
    lines.push('');
  }
  lines.push(`${suggestions.length} match${suggestions.length === 1 ? '' : 'es'} in target repo.`);
  lines.push('');

  for (const s of suggestions) {
    lines.push(renderOneSuggestion(s));
  }

  return lines.join('\n');
}

function renderSummary(draft: FixDraft): string {
  const t = draft.totals;
  const lines: string[] = [];

  lines.push('## Summary');
  lines.push('');
  lines.push(`- Package: **${draft.packageName}** ${draft.oldVersion} → ${draft.newVersion}`);
  lines.push(`- Target repo: \`${draft.targetRepoPath}\``);
  lines.push(`- Symbols with matches: **${t.symbolsWithMatches}**`);
  lines.push(`- Total suggestions: **${t.suggestions}**`);
  lines.push(`- High confidence: ${t.highConfidence}`);
  lines.push(`- Medium confidence: ${t.mediumConfidence}`);
  lines.push(`- Low confidence: ${t.lowConfidence}`);
  lines.push(`- Requires manual review: ${t.manualReview}`);
  lines.push(`- Generation errors: ${t.errors}`);
  lines.push('');

  if (t.suggestions === 0) {
    lines.push('No real usages were found in the target repo, so no fixes were drafted.');
    lines.push('Either the upgrade is breaking upstream but your codebase is unaffected (a real negative),');
    lines.push("or the LLM verdict said the upgrade wasn't breaking and the scan was skipped.");
    lines.push('');
  }

  return lines.join('\n');
}

/** Render the full draft as a Markdown document. */
export function renderReport(draft: FixDraft): string {
  const parts: string[] = [];

  parts.push(`# DriftGuard Fix Report — ${draft.packageName} ${draft.oldVersion} → ${draft.newVersion}`);
  parts.push('');
  parts.push(`Target: \`${draft.targetRepoPath}\``);
  parts.push('');
  parts.push('---');
  parts.push('');

  parts.push(renderSummary(draft));

  const symbols = Object.keys(draft.bySymbol).sort();
  if (symbols.length > 0) {
    for (const sym of symbols) {
      parts.push(renderSymbolBlock(sym, draft.bySymbol[sym]));
    }
  }

  parts.push('');
  parts.push('---');
  parts.push('');
  parts.push('_Generated by DriftGuard. Each fix is an LLM draft; please review before applying._');

  return parts.join('\n');
}

/**
 * Write the report to disk and return the path. Creates the reports/ dir
 * if it does not exist.
 */
export function saveReport(draft: FixDraft): string {
  const path = reportFileName(draft);
  fs.mkdirSync(REPORTS_DIR, { recursive: true });
  fs.writeFileSync(path, renderReport(draft), 'utf8');
  return path;
}

/** Print a short summary of the report to the console. */
export function announceReport(draft: FixDraft, savedPath: string): string[] {
  const lines: string[] = [];
  const t = draft.totals;

  lines.push('');
  lines.push('FIX DRAFT COMPLETE');
  lines.push('------------------');
  lines.push(`  symbols with matches : ${t.symbolsWithMatches}`);
  lines.push(`  suggestions generated : ${t.suggestions}`);
  lines.push(`  high / medium / low   : ${t.highConfidence} / ${t.mediumConfidence} / ${t.lowConfidence}`);
  lines.push(`  requires manual review: ${t.manualReview}`);
  lines.push(`  generation errors     : ${t.errors}`);
  lines.push(`  report saved to       : ${savedPath}`);
  lines.push('');
  lines.push('Read the report, decide which fixes to apply, and skip the manual-review ones.');

  return lines;
}